### ISSUE TITLE
Any plans for craft 4 update?

### ISSUE THREAD

**Issue by ursbraem** [venveo/craft-documentsearch#10]
Hi! Do you still maintain the plugin and do you intend to update it for craft 4?
We are highly interested in the functionality; if you'd decide to abandon it, we might also be of help.

**Comment by Mosnar** [comment]
It's been on the list! It hasn't been a high priority since it's not very widely used and we haven't needed it internally for Craft 4 yet. That said, it should be a very quick update since it's not a very complex plugin. If you'd like to take a stab at a PR, you're more then welcome to! If not, we'll get it updated in the next week or two.

**Comment by ursbraem** [comment]
Thanks! That is great. We're including it in a quote now. I guess you will be quicker than our project will start, in the latter case, we can look at it then. 👍

**Comment by Mosnar** [comment]
Just tagged 4.0.0, let me know if you have any issues!

**Comment by ursbraem** [comment]
Awesome! Thank you!
